### ISSUE TITLE
optimize the release process

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/multi-repo-issue#79] opened 2021-02-23 10:54 UTC
The goal of this task is to make the release process as short as possible without manual steps. Ideally starting a script will do the perform all of the steps.

Do this for all major py repos:
- [ ] ocean.py - [ocean.py#179](https://github.com/oceanprotocol/ocean.py/issues/179)
- [ ] provider
- [ ] aquarius

**Comment by calina-c** [comment] 2021-09-02 05:14
I moved this to the "PM to discuss" column, since I understand there is still disagreement on how we release versions of our software. We should probably have a call and make some decisions together.

**Comment by calina-c** [comment] 2021-09-06 09:02
Please note that the Aquarius readme should be updated with the final release process, since that section/linked README does not exist in Aquarius yet.

**Comment by calina-c** [comment] 2021-09-07 09:06
@trentmc @alexcos20 @AnaLoznianu Do you guys think we can discuss this one during our grooming meeting today?

**Comment by mihaisc** [comment] 2021-09-07 09:54
Also for aquarius/provider/subgraph i would suggest to partially automatize the release a bit. What had in mind is something like : when a release is made an issue is automatically created with the one who made the release (or the whole team from that repo) , Marian and someone from the market (maybe me and/or Matthias ). On that issue we need to figure out if there are breaking changes in the new release and sync the deployment of the new release with the market. 

Example flow for aqua release : 
- deploy on aquarius2
- create pr on market and test it with aquarius2
- swap aquarius2 with main deployment
- merge pr on market

The purpose of the issue is to just have a common place to track all these and not forget deployments.

**Comment by trentmc** [comment] 2021-09-07 13:31
We talked about this issue in BE mtg today. We're not going to fully automate, the brittelness isn't worth the effort.

I believe we decided on (a) close this issue (b) have a specific issue for aqua (c) have a specific issue for provider. 

Did I remember that correctly?

**Closed** 2022-02-16 05:25 UTC
Labels: Type: Documentation, Type: Epic
